modes = {
    'identity': {
        'identity': ['zhu', 'zhong', 'fan', 'nei'],
        'globalSkill': ['updateAI', 'onPhaseUseAfter', 'onPhaseAfter'],
        'inPile': {
            'basic': ['sha', 'shan', 'tao', 'jiu'],
            'trick': {
                'normal': ['guohe', 'shunshou', 'wuzhong', 'wanjian', 'nanman', 'juedou'],
                'delay': [],
            },
            'equip': {
                'weapon': ['zhuge', 'guanshi'],
                'armor': ['bagua', 'renwang'],
                'defendHorse': [],
                'attackHorse': []
            },
        },
        'inPile_nature': ['fire', 'thunder'],
        'cards': [
            ['wanjian', 'heart', 1, {}],
            ['zhuge', 'diamond', 1, {}],
            ['zhuge', 'diamond', 1, {}],
            ['juedou', 'diamond', 1, {}],
            ['juedou', 'diamond', 1, {}],
            ['zhuge', 'club', 1, {}],
            ['juedou', 'club', 1, {}],
            ['juedou', 'spade', 1, {}],
            ['juedou', 'club', 1, {}],
            ['juedou', 'spade', 1, {}],
            ['shan', 'heart', 2, {}],
            ['shan', 'diamond', 2, {}],
            ['shan', 'heart', 2, {}],
            ['shan', 'diamond', 2, {}],
            ['tao', 'diamond', 2, {}],
            ['sha', 'club', 2, {}],
            ['bagua', 'club', 2, {}],
            ['bagua', 'club', 2, {}],
            ['bagua', 'club', 2, {}],
            ['renwang', 'club', 2, {}],
            ['renwang', 'club', 2, {}],
            ['bagua', 'spade', 2, {}],
            ['tao', 'heart', 3, {}],
            ['shan', 'diamond', 3, {}],
            ['tao', 'diamond', 3, {}],
            ['sha', 'club', 3, {}],
            ['jiu', 'club', 3, {}],
            ['guohe', 'spade', 3, {}],
            ['shunshou', 'spade', 3, {}],
            ['guohe', 'spade', 3, {}],
            ['guohe', 'spade', 3, {}],
            ['shunshou', 'spade', 3, {}],
            ['guohe', 'spade', 3, {}],
            ['jiu', 'spade', 3, {}],
            ['tao', 'heart', 4, {}],
            ['sha', 'heart', 4, {'nature': 'fire'}],
            ['sha', 'diamond', 4, {'nature': 'fire'}],
            ['shan', 'diamond', 4, {}],
            ['sha', 'club', 4, {}],
            ['guohe', 'club', 4, {}],
            ['guohe', 'club', 4, {}],
            ['sha', 'spade', 4, {'nature': 'thunder'}],
            ['shunshou', 'spade', 4, {}],
            ['guohe', 'spade', 4, {}],
            ['shunshou', 'spade', 4, {}],
            ['guohe', 'spade', 4, {}],
            ['sha', 'spade', 4, {'nature': 'thunder'}],
            ['tao', 'heart', 5, {}],
            ['shan', 'diamond', 5, {}],
            ['guanshi', 'diamond', 5, {}],
            ['guanshi', 'diamond', 5, {}],
            ['guanshi', 'diamond', 5, {}],
            ['sha', 'diamond', 5, {'nature': 'fire'}],
            ['sha', 'club', 5, {}],
            ['sha', 'club', 5, {'nature': 'thunder'}],
            ['sha', 'spade', 5, {'nature': 'thunder'}],
            ['tao', 'heart', 6, {}],
            ['tao', 'heart', 6, {}],
            ['sha', 'diamond', 6, {}],
            ['shan', 'diamond', 6, {}],
            ['shan', 'diamond', 6, {}],
            ['sha', 'club', 6, {}],
            ['sha', 'club', 6, {'nature': 'thunder'}],
            ['sha', 'spade', 6, {'nature': 'thunder'}],
            ['tao', 'heart', 7, {}],
            ['sha', 'heart', 7, {'nature': 'fire'}],
            ['sha', 'diamond', 7, {}],
            ['shan', 'diamond', 7, {}],
            ['shan', 'diamond', 7, {}],
            ['sha', 'club', 7, {}],
            ['nanman', 'club', 7, {}],
            ['nanman', 'club', 7, {}],
            ['sha', 'club', 7, {'nature': 'thunder'}],
            ['sha', 'spade', 7, {}],
            ['nanman', 'spade', 7, {}],
            ['nanman', 'spade', 7, {}],
            ['sha', 'spade', 7, {'nature': 'thunder'}],
            ['tao', 'heart', 8, {}],
            ['wuzhong', 'heart', 8, {}],
            ['wuzhong', 'heart', 8, {}],
            ['shan', 'heart', 8, {}],
            ['sha', 'diamond', 8, {}],
            ['shan', 'diamond', 8, {}],
            ['shan', 'diamond', 8, {}],
            ['sha', 'club', 8, {}],
            ['sha', 'club', 8, {}],
            ['sha', 'club', 8, {'nature': 'thunder'}],
            ['sha', 'spade', 8, {}],
            ['sha', 'spade', 8, {}],
            ['sha', 'spade', 8, {'nature': 'thunder'}],
            ['tao', 'heart', 9, {}],
            ['wuzhong', 'heart', 9, {}],
            ['wuzhong', 'heart', 9, {}],
            ['shan', 'heart', 9, {}],
            ['sha', 'diamond', 9, {}],
            ['shan', 'diamond', 9, {}],
            ['jiu', 'diamond', 9, {}],
            ['sha', 'club', 9, {}],
            ['sha', 'club', 9, {}],
            ['jiu', 'club', 9, {}],
            ['sha', 'spade', 9, {}],
            ['sha', 'spade', 9, {}],
            ['jiu', 'spade', 9, {}],
            ['sha', 'heart', 10, {}],
            ['sha', 'heart', 10, {}],
            ['sha', 'heart', 10, {'nature': 'fire'}],
            ['sha', 'diamond', 10, {}],
            ['shan', 'diamond', 10, {}],
            ['shan', 'diamond', 10, {}],
            ['sha', 'club', 10, {}],
            ['sha', 'club', 10, {}],
            ['sha', 'spade', 10, {}],
            ['sha', 'spade', 10, {}],
            ['shan', 'heart', 11, {}],
            ['wuzhong', 'heart', 11, {}],
            ['wuzhong', 'heart', 11, {}],
            ['sha', 'heart', 11, {}],
            ['shan', 'diamond', 11, {}],
            ['shan', 'diamond', 11, {}],
            ['shan', 'diamond', 11, {}],
            ['sha', 'club', 11, {}],
            ['sha', 'club', 11, {}],
            ['shunshou', 'spade', 11, {}],
            ['shunshou', 'spade', 11, {}],
            ['tao', 'heart', 12, {}],
            ['guohe', 'heart', 12, {}],
            ['guohe', 'heart', 12, {}],
            ['shan', 'heart', 12, {}],
            ['tao', 'diamond', 12, {}],
            ['guohe', 'spade', 12, {}],
            ['guohe', 'spade', 12, {}],
            ['shan', 'heart', 13, {}],
            ['sha', 'diamond', 13, {}],
            ['nanman', 'spade', 13, {}],
            ['nanman', 'spade', 13, {}],
        ]
    }
}
